### ISSUE TITLE
Indeterminate state

### ISSUE THREAD

**Issue by JosefJezek** [PolymerElements/paper-checkbox#112]
Could you add Indeterminate state just like element tristate-checkbox?

https://github.com/johnthad/tristate-checkbox

**Comment by notwaldorf** [comment]
We've had an in depth discussion about this on this thread as to why this shouldn't be a property of the checkbox, but a separate element in itself: https://github.com/PolymerElements/paper-checkbox/issues/33

The feature request for a checkable node element is here: https://github.com/PolymerElements/paper-elements/issues/24
