### ISSUE TITLE
Set checked label color 

### ISSUE THREAD

**Issue by deadlyfingers** [PolymerElements/paper-checkbox#115]
Would also be nice to be able to set the checked label color.
I'm plugging this with !important style in my CSS - maybe there is a better way?
```
paper-checkbox[checked] div {
	color: green !important;
}
```

**Comment by bicknellr** [comment]
Hmm, here's the demo I came up with for this: http://jsbin.com/zisaca/1/edit?html,output ; it seems like the style shim is removing the `[checked]` portion of the selector when rewrites it for Shady DOM. This looks like a bug but I'll do a bit more investigation next week.

**Comment by bicknellr** [comment]
I talked with @sorvell who explained that the reason my demo doesn't work is a limitation of the style shim. It can't know when the applicability of a CSS rule to paper-checkbox (or any element) changes, so it can't know when to rewrite the internal styles of that paper-checkbox which are faking the `--paper-checkbox-label-color` CSS variable.

For the moment, the way to get around this is to call `updateStyles` of the checkbox whenever [checked changes](http://jsbin.com/wowewu/1/edit?html,output). I'll look into adding a new CSS variable like `--paper-checkbox-checked-label-color` and maybe also `--paper-checkbox-unchecked-label-color` for consistency.

**Comment by bicknellr** [comment]
Fixed in #120.
