### ISSUE TITLE
Multiple checkboxes change at once when inside a nested `dom-if`

### ISSUE THREAD

**Issue by lbustelo** [PolymerElements/paper-checkbox#117]
### Description
Using `paper-checkbox` in a nested `dom-if` template is causing more than one checkbox to change state when I interact with one.

```html
<template is='dom-bind'>
    <table>
        <template is="dom-repeat" items="[[true, false, true],[false, false, true],[true, false, true]]" as="row">
            <tr>
                <template is="dom-repeat" items="[[row]]" as="col">
                    <td><paper-checkbox checked="{{col}}">{{col}}</paper-checkbox>
                    </td>
                </template>
            </tr>
        </template>
    </table>
</template>
```

### Expected outcome
Only one checkbox would change at a time

### Actual outcome
More than one checkbox changes

### Live Demo
https://jsbin.com/hidaridoja/edit?html,output

![checkbox_error](https://cloud.githubusercontent.com/assets/2474841/14869828/a1f89f86-0c9b-11e6-8833-c5ebde974caf.gif)

### Steps to reproduce

Click multiple times in the checkboxes in the middle column. Eventually you will see how more than one checkbox changes state.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8 ?
- [ ] Safari 7 ?
- [ ] Edge ?
- [ ] IE 11 ?
- [ ] IE 10 ?

**Comment by ktiedt** [comment]
note: this problem goes away if the array items are objects and you track the state as a property of the object, but anything else appears to cause the bindings to get confused.

**Comment by arthurevans** [comment]
What @ktiedt said. The issue here is that the array items need to be _unique_ for Polymer to track them, so it can't if they're bare primitives like true, false.

```
 <template is='dom-bind'>
    <table>
        <template is="dom-repeat" items='[[{"checked": true}, {"checked": false}, {"checked": true}],[{"checked": false}, {"checked": false}, {"checked": true}],[{"checked": true}, {"checked": false}, {"checked": true}]]' as="row">
            <tr>
                <template is="dom-repeat" items="[[row]]" as="col">
                    <td><paper-checkbox checked="{{col.checked}}">{{col.checked}}</paper-checkbox>
                    </td>
                </template>
            </tr>
        </template>
    </table>
</template>
```

**Comment by lbustelo** [comment]
@ktiedt So the problem is not isolated to booleans, it will happen if I have numbers too? That feels limiting. Why no use the index as an identifier?

**Comment by arthurevans** [comment]
@lbustelo Polymer generates a key that it uses to track array items. That way, the effects inside a `dom-repeat` can be bound directly to a specific array item. If you add or delete items from the array, the key for the existing items doesn't change.

**Comment by lbustelo** [comment]
Makes sense implementation wise. But it seems that for simple cases, this design makes things harder for the user.  Hopefully you can appreciate that my use case is simple and common.

**Comment by arthurevans** [comment]
Yeah. At the minimum, this should be documented, and it isn't. Mea culpa.

There's also an open issue to fix this by creating unique wrappers when you use primitives directly:

https://github.com/Polymer/polymer/issues/1913

I recommend following that ticket. I'm not sure of its current status, but I don't expect any action on it in the immediate future as the team is heads-down on other stuff ATM.

**Comment by arthurevans** [comment]
Added a doc bug for this as well: https://github.com/Polymer/docs/issues/1616

**Comment by bicknellr** [comment]
Closing as this isn't a paper-checkbox bug; thank you for taking the time to report this though!

**Comment by lbustelo** [comment]
Thanks guys. I'm sorry I did not close myself.
