### ISSUE TITLE
Mixins for checkboxContainer and checkboxLabel to allow for styling flexibility

### ISSUE THREAD

**Issue by helenxywu** [PolymerElements/paper-checkbox#119]
It would be nice to have mixins to apply to checkboxContainer and checkboxLabel to allow for more flexible styling of the checkbox

**Comment by notwaldorf** [comment]
@helenxywu What kind of styling are you looking for? The label is already in your light dom, so you should be able to customize it as much as you want: http://jsbin.com/xefotiq/edit?html,output

The `checkboxContainer` hold the checkbox and the checkmark, and I'm worried that if you start applying arbitrary styles, this will literally break your checkbox. For example, in the JSBin I linked to, if I just change the width of the container, disasters happen:
<img width="240" alt="screen shot 2016-05-23 at 10 38 57 am" src="https://cloud.githubusercontent.com/assets/1369170/15478971/9ab4b3e0-20d2-11e6-92b3-454a1a82df93.png">

**Comment by notwaldorf** [comment]
After talking to @bicknellr, I think a mixin for the label is probably alright (so that you can style all the checkboxes ever at once), and myabe just a custom property for the `vertical-align`, since that's probably all you need :)
