### ISSUE TITLE
Add support for indeterminate state

### ISSUE THREAD

**Issue by jouni** [PolymerElements/paper-checkbox#122]
To be as usable as a native checkbox input, paper-checkbox should support the `indeterminate` property, as in the state when the value is neither true or false, which is visually commonly indicated with a dash inside the checkbox element.

[Example of a native checkbox input in the indeterminate state](https://jsfiddle.net/5ypoz0ym/)

The state is needed for instance in a data table with a “select all” feature, where the checkbox that toggles the selection of all/no items should indicate if there are some items selected in the table.

**Comment by notwaldorf** [comment]
We've had an in depth discussion about this on this thread as to why this shouldn't be a property of the checkbox, but a separate element in itself: https://github.com/PolymerElements/paper-checkbox/issues/33

The feature request for a checkable node element is here: https://github.com/PolymerElements/paper-elements/issues/24

**Comment by jouni** [comment]
Ah, sorry about not searching old issues first, my bad. Thanks for the response!
