### ISSUE TITLE
Allow the label to be positioned on the left side

### ISSUE THREAD

**Issue by viftodi** [PolymerElements/paper-checkbox#125]
Currently the label is positioned on the right side and there is no direct way to position it on the left side.

It is useful in certain circumstances to position the label on the left side.

This component should allow such customization.

This issue is a sort of duplicate of the same one on the toggle-button component available on this link (https://github.com/PolymerElements/paper-toggle-button/issues/94)

**Comment by hemantjadon** [comment]
Hi can i try to fix this ?

**Comment by bicknellr** [comment]
@notwaldorf just pointed out to me that iron-label already handles this: http://jsbin.com/kuqihu/1/edit?html,output.

**Comment by bicknellr** [comment]
Let me know if this doesn't cover your use case or, if it does, I think we can close this and PolymerElements/paper-toggle-button#94.

**Comment by hemantjadon** [comment]
`iron-label` works fine but will it not be nice to enclose this in element in as a property of `paper-checkbox` and `paper-toggle-button`??

we can wrap the `toggle-container` and `toggle-label` div in a `toggle-container-label-group` and use `display:flex`, `flex-direction:row` for right label, and `flex-direction:row-reverse` for left label

Reference to : PolymerElements/paper-toggle-button#94, PolymerElements/paper-toggle-button#95

**Comment by hemantjadon** [comment]
What Label will be preferred in situation like we have both `iron-label` and and `<content></content>` in the `paper-checkbox` and `paper-toggle-button`.

Ref : http://jsbin.com/yunohijowu/edit?html,output

**Comment by hemantjadon** [comment]
I have tried to implement the wrapping in `class:flex` but it somehow breaks the previous `checkbox line-height` test suite. So it will require some minor changes in the test.

I can submit the PR.

**Comment by viftodi** [comment]
@bicknellr iron-label indeed seems like a viable solution, I will take that into consideration, thank you for the tip.

I personally think that it's strange that when you have a paper-checkbox component, that has a label it does not allow it directly to be positioned on either side.

I would consider it cleaner if for example the paper-checkbox component didn't have a label at all, and you'd link it with a label with an iron label, similar to in html with label for.
This way the paper-checkbox is just a basic component and you compose it into a more complex one with a label if you desire.

But since it has a label that is part of the component, I find it strange that you can't customize it's position as are cases when you require it to be on the other side,  either because of languages that are read right to left, or because of certain form layouts or perhaps even other reasons.

Since you gave me a viable solution, that should cover my needs, the example is sufficient to allow me to make my own component if needed.

It is up to you to consider if paper-checkbox should handle the customization of the position of label directly or not.

Thank you.

**Comment by bicknellr** [comment]
> I would consider it cleaner if for example the paper-checkbox component didn't have a label at all,

@viftodi Yeah, that's the motivation. We can't currently remove the label from paper-checkbox since it would be a breaking change but its something we plan for the future. Using iron-label (or something similar) would become the expected way to do this and, given that it works now, I think it's ok (and preferable from a maintenance standpoint) not to provide this flexibility within paper-checkbox itself.

> languages that are read right to left,

With regards to RTL, because the checkbox and the label are inline, the box will be positioned to the right of the label automatically when paper-checkbox is in an RTL area of the page. Also, this is true both when using the built-in label or an iron-label. [Here's a demo.](http://jsbin.com/savonun/1/edit?html,output)

**Comment by bicknellr** [comment]
@hemantjadon I'd recommend against using the built-in label if you're using an iron-label ([slightly modified version of your demo](http://jsbin.com/yogejo/edit?html,output)). I noticed some inconsistency about what's read in the mixed case (using VoiceOver at least) but moving everything outside the paper-checkbox seems to label both properly.

**Comment by bicknellr** [comment]
I'm going to go ahead and close these issues and their associated PRs (w/ links here for reference); thanks for sending them!

**Comment by MarcMouallem** [comment]
#### Easiest fix 
Apply `flex-direction: row-reverse` to `<paper-checkbox>`.
####
@bicknellr As touched upon, at least for the moment the `<iron-label>` solution is inconsistent with the design of `<paper-checkbox>` which has multiple styling mixins specificly for the label. Refer to `<paper-checkbox>` documentation [here](https://www.webcomponents.org/element/PolymerElements/paper-checkbox/elements/paper-checkbox).

In addition, placing the label outside of `<paper-checkbox>` would not be conducive to label styling responsive to the checked state nor conducive to the ability to toggle the checked state by tapping the label.

I understand this is not a priority, and I can not speak for all developers, but acknowledging such issues is meaningful.
