### ISSUE TITLE
Checkbox is not displayed and paper-ripple cover all page

### ISSUE THREAD

**Issue by matheusdavidson** [PolymerElements/paper-checkbox#13]
Not sure if i did anything wrong, on the demo page works well but when i install it on my app and place it on the page the checkbox is not displayed and paper-ripple cover all page, i mean, if i click anywhere on the page it shows the ripple, see image:

![checkbox](https://cloud.githubusercontent.com/assets/2229994/7552789/12dd4978-f6a3-11e4-99e2-4310af17f9dc.png)

**Comment by matheusdavidson** [comment]
The checkbox should be before "Notification" label

**Comment by matheusdavidson** [comment]
After a few goggling around i think its a problem with vulcanize and CSS import as the css is placed in vulcanize.html without any style tag

**Comment by notwaldorf** [comment]
The demo looks good locally, so I think you're right that this is a vulcanize issue. Going to close this issue.
