### ISSUE TITLE
material design spec audit - few changes needed

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/paper-checkbox#15]
* Ripple should always be centered, regardless of where the touch/click occured.
* Opacity of ripple _might_ be a bit high: http://www.google.com/design/spec/components/selection-controls.html#

**Comment by notwaldorf** [comment]
Fixed with https://github.com/PolymerElements/paper-checkbox/pull/17

**Comment by blasten** [comment]
This is all fixed now!
