### ISSUE TITLE
Closure compiler error, parseFloat called with 2 arguments.

### ISSUE THREAD

**Issue by freshp86** [PolymerElements/paper-checkbox#188]
In Chromium, we run Polymer elements through the Closure compiler. When trying to update to 2.0.1, the following error was revealed, from https://github.com/PolymerElements/paper-checkbox/blob/befe1605a5f461cd8e634a6c82189e5997c91075/paper-checkbox.html#L280.

```
## /usr/workspace/chromium/src/third_party/polymer/v1_0/components-chromium/paper-checkbox/paper-checkbox-extracted.js:42: ERROR - Function parseFloat: called with 2 argument(s). Function requires at least 1 argument(s) and no more than 1 argument(s).
##             var checkboxSize = parseFloat(checkboxSizeText, 10);
##                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Per docs, parseFloat() only accepts a single parameter, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat.

**Comment by freshp86** [comment]
cc @azakus

**Comment by notwaldorf** [comment]
cc @bicknellr
