### ISSUE TITLE
extending the element

### ISSUE THREAD

**Issue by zishanj** [PolymerElements/paper-checkbox#25]
Is it possible to extend this element? I have seen the docs for 0.5 but that is outdated and doesn't support this version. Any other link to doc that tells how to extend this 1.0?

Btw. if you use native HTML `input` element like it's used in `paper-input` with base element `paper-input-container` then it will be much easy to bind it with other libraries like AngularJS.

**Comment by notwaldorf** [comment]
Unfortunately, in Polymer 1.0 you can only extend native elements, not custom elements. Extending the `input` element means we can't add any styling (see `iron-input`, which is exactly that), which wouldn't help style the `paper-checkbox` the way it is now.
