### ISSUE TITLE
paper-checkbox and iron-form compatibility

### ISSUE THREAD

**Issue by atoy40** [PolymerElements/paper-checkbox#38]
Hello,

it seems paper-checkbox (and paper-toggle) doesn't implement Polymer.IronFormElementBehavior, so it's not handled by the iron-form element (at least the .serialize() output)

Anthony

**Comment by notwaldorf** [comment]
You're completely right. I am working on a fix, hopefully it should be done soon.

**Comment by atoy40** [comment]
this starting iron-checked-element-behavior smells good to me :)

**Comment by notwaldorf** [comment]
@atoy40 Hopefully! :)

**Comment by MelHarbour** [comment]
Really keen to see this get fixed!

**Comment by MelHarbour** [comment]
@notwaldorf I think this still needs to be added to paper-toggle-button?

**Comment by notwaldorf** [comment]
@MelHarbour Yup! They should be ready by today/tomorrow! :)

**Comment by yglodt** [comment]
When I submit an iron-form with several paper-checkboxes they get posted like this:

nameOfInput:a4a1920b-1f51-4b7b-830b-877fad5fcc0c,a6905094-eeed-47a6-bec7-872f88b24499

This is not the expected behaviour I guess ?!

**Comment by notwaldorf** [comment]
@yglodt I filed https://github.com/PolymerElements/iron-ajax/issues/114

**Comment by yglodt** [comment]
Thanks @notwaldorf ! Note that I submit the form with it's submit method:

    <paper-button raised onclick="document.getElementById('formId').submit()">Save</paper-button>

**Comment by notwaldorf** [comment]
@yglodt it's not the submitting that's the problem. The `iron-form` uses `iron-ajax` for the actual http request, and `iron-ajax` hasn't formed a good opinion on how to query string encode arrays. Thanks for spotting this! :)
