### ISSUE TITLE
paper-checkbox and vulcanize

### ISSUE THREAD

**Issue by keithstric** [PolymerElements/paper-checkbox#42]
Not sure if this is the proper place to report this or if it should be an issue with webcomponents.js or vulcanize. 

In the Safari Browser, a non-vulcanized paper-checkbox works perfectly. Once vulcanize takes place the actual checkbox does not render (only the label is visible) and the paper-ripple covers everything above paper-checkbox which results in a ripple no matter where on the page above the checkbox a click occurs.

Investigation into this shows that the styles for the "paper-checkbox #checkbox.paper-checkbox" are not present in Safari for a vulcanized paper-checkbox. I did not compare styles going up the DOM tree so not sure if something is missing there or not.

UPDATE 1:
Don't know if this helps or just clutters this issue. But, if I include these styles in my CSS it fixes the issue I described above (copied from Chrome Developer Tools and pasted into stylesheet):

paper-checkbox {
	display: inline-block;
	white-space: nowrap;
}
#checkbox.checked {
	background-color: @default-primary-color;
	border-color: @default-primary-color;
}
#checkboxContainer.paper-checkbox {
	display: inline-block;
	position: relative;
	width: 18px;
	height: 18px;
	cursor: pointer;
	-webkit-transform: translateZ(0);
	transform: translateZ(0);
	vertical-align: middle;
}
#checkboxLabel.paper-checkbox {
	position: relative;
	display: inline-block;
	vertical-align: middle;
	padding-left: 8px;
	white-space: normal;
	pointer-events: none;
}
#checkbox.paper-checkbox {
	position: relative;
	box-sizing: border-box;
	height: 100%;
	border: solid 2px;
	border-radius: 2px;
	pointer-events: none;
	-webkit-transition: background-color 140ms, border-color 140ms;
	transition: background-color 140ms, border-color 140ms;
}
#checkbox.checked.paper-checkbox #checkmark.paper-checkbox {
	-webkit-animation: checkmark-expand 140ms ease-out forwards;
	animation: checkmark-expand 140ms ease-out forwards;
}
#checkmark.paper-checkbox {
	-webkit-transform: rotate(45deg);
	transform: rotate(45deg);
	position: absolute;
	top: -1px;
	left: 4px;
	width: 5px;
	height: 10px;
	border-style: solid;
	border-top: none;
	border-left: none;
	border-right-width: 2px;
	border-bottom-width: 2px;
	border-color: white;
}

**Comment by notwaldorf** [comment]
@azakus would you mind taking a look at this? I'm not a good `vulcanize` person to ask :(

**Comment by notwaldorf** [comment]
@keithstric are you still having issues, or should I close it?

**Comment by notwaldorf** [comment]
I'll close this since it looks inactive. Please reopen this if you're still having issues.
