### ISSUE TITLE
Add 'indeterminate' state.

### ISSUE THREAD

**Issue by grokys** [PolymerElements/paper-checkbox#43]
An indeterminate state would be very useful, and in fact necessary in my case, which is that of a treeview of checkable items.

An idea for an API: an `indeterminate` property that when set interprets the `checked` property as `true` for checked, `false` for unchecked and `null` or `undefined` as indeterminate.

**Comment by notwaldorf** [comment]
Please check the discussion on this thread: https://github.com/PolymerElements/paper-checkbox/issues/33

TL: DR; Outside of a tree-like structure, this doesn't make any sense to be added to a checkbox (most checkboxes are just a list of things). This should be a `tree-checkable-element` or something like that.

I've created https://github.com/PolymerElements/paper-elements/issues/24 as a feature request
