### ISSUE TITLE
can't use keyboard to toggle the checkbox

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/paper-checkbox#46]
on paper-checkbox (v1.0.5) demo page:
- hit `tab` key to focus one of the checkbox
- hit `enter`/`spacebar` to toggle the checkbox (works fine as expected)
- use mouse to click on the checkbox to toggle
- hit `tab` key to focus the next checkbox
- now hit `enter`/`spacebar` again to toggle the checkbox (not working!)

**Comment by notwaldorf** [comment]
@cdata Does this look familiar? Something something a11y keys?

**Comment by notwaldorf** [comment]
I can't reproduce this anymore (I think this was a gestures bug and was fixed upstream). Please re-open if you can still repro this.
