### ISSUE TITLE
Distinguish focused from unofcused state

### ISSUE THREAD

**Issue by dandv** [PolymerElements/paper-checkbox#57]
At https://www.polymer-project.org/1.0/components/paper-elements/demo.html#paper-checkbox, if you tab among checkboxes, there's no indication which one has focus.

See also https://github.com/thomaspark/bootswatch/issues/505#issuecomment-136758520

**Comment by notwaldorf** [comment]
I don't know what this demo is, but I feel it's a demo of the 0.5 elements. Our new, 1.0 element demos live at https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html

**Comment by dandv** [comment]
That demo has `1.0` in the URL, and is what shows up first when Googling for `polymer paper demo`.
