### ISSUE TITLE
Set the website of this GitHub repo to the demo

### ISSUE THREAD

**Issue by dandv** [PolymerElements/paper-checkbox#58]
https://www.polymer-project.org/1.0/components/paper-elements/demo.html#paper-checkbox

**Comment by notwaldorf** [comment]
That is not the correct link to the demo. The 1.0 paper-checkbox demo is at https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html

**Comment by dandv** [comment]
Fine. Why don't the older demos that show up first in Google search results should link to the correct demo?

![image](https://cloud.githubusercontent.com/assets/33569/9619619/b00628be-50c6-11e5-8ca7-dda3afe791a4.png)

**Comment by notwaldorf** [comment]
:pager: @arthurevans
