### ISSUE TITLE
Checkboxes don't work well in a column layout

### ISSUE THREAD

**Issue by lkovaleva** [PolymerElements/paper-checkbox#61]
Code:
```
<div style="-webkit-column-count:4;">
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
  <paper-checkbox>Checkbox</paper-checkbox>
</div>
```

Click some checkboxes to turn them on, and observe and for some reason the white checkmark is only visible in the first column, the rest show a solid square when checked
![image](https://cloud.githubusercontent.com/assets/14207087/9798948/1e3bfa86-57b9-11e5-8c69-99629d4c62e5.png)

**Comment by notwaldorf** [comment]
Blerg, I think this is the `-webkit-column-count:4;` style being weird. If I use a flexbox column layout, everything looks fine. I also only see this in Chrome and not Safari, so I'm think Chrome has a bug in its implementation of `-webkit-column-count:4;`

**Comment by notwaldorf** [comment]
Yeah, even this, which just uses native elements, will make the label jump around. I will file a bug in Chrome, but I don't think there's anything we can do here :(
```
<div style="-webkit-column-count:4; width:400px;">
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
  <input type="checkbox">Checkbox<br/>
</div>
```

**Comment by notwaldorf** [comment]
(added to existing bug https://code.google.com/p/chromium/issues/detail?id=530260). Closing this since unfortunately this isn't a Polymer bug.

**Comment by lkovaleva** [comment]
Thanks for digging into it! If you don't mind - what's the equivalent flexbox layout that you used?

**Comment by notwaldorf** [comment]
I had just hacked it to fit into 4 columns by wrapping it, but I'm not super sure what you want the end result to be:

```css
<style is="custom-style">
.container {
  @apply(--layout-wrap);
  @apply(--layout-inline);
}
paper-checkbox {
  display: block;
  width: 350px;
}
</style>
```
And adding the `container` class to your top level div.

**Comment by lkovaleva** [comment]
Thank you
