### ISSUE TITLE
Extra Padding when checkboxLabel is empty

### ISSUE THREAD

**Issue by Gwalks91** [PolymerElements/paper-checkbox#67]
The padding for the "checkboxLabel" div stays even when the label is empty which causes the check box to be slightly bigger and mess up some styling. Is there a way around this without having to custom style every check box that doesn't have a label?
![checkbox_styling](https://cloud.githubusercontent.com/assets/6686631/10500849/8f1d0744-7290-11e5-957d-b33b1954b3b6.png)

**Comment by chunkzer** [comment]
Just made a PR with a fix for your problem. Please check it out. : )

**Comment by Gwalks91** [comment]
Awesome thanks for the fix

**Comment by Gwalks91** [comment]
@chunkzer I think the fix you originally proposed would work but the --paper-checkbox-label-spacing of 0 does not seem to totally fix the problem. 
![checkbox_styling](https://cloud.githubusercontent.com/assets/6686631/10529989/b84d3cac-7357-11e5-8625-fe34938e65dd.png)

**Comment by chunkzer** [comment]
@Gwalks91 I'm not sure I understand what problem you are referring to. Is it that there's still a div with id="checkboxLabel" (even if it's not being displayed)?

**Comment by Gwalks91** [comment]
It seems like it is still being displayed even though it has a width and height of 0. When I add a display:none on the checkboxLabel in the chrome debugger the small space next the the checkbox in the picture from my last post goes away. The solution that you first proposed would have fixed it the no-label attribute but it was not implemented in the actual commit to Polymer

**Comment by notwaldorf** [comment]
I've landed https://github.com/PolymerElements/paper-checkbox/pull/66, which adds a custom property to control the padding between the text and the label. You can set that to 0 if you know you're not going to have a label:

```css
paper-checkbox.nolabel {
  --paper-checkbox-label-spacing: 0px;
}
```
I think a `nolabel` attribute would be a bit confusing (what happens if you have a label and a `nolabel` attribute? which one wins?)

**Comment by bpinney** [comment]
Awesome, thanks. This should be included in the documentation.
