### ISSUE TITLE
paper-checkbox and paper-behaviors error

### ISSUE THREAD

**Issue by jeremiahgibson91** [PolymerElements/paper-checkbox#69]
Error: Uncaught TypeError: this._ripple.uiDownAction is not a function

The issue here is a bit difficult to track down but essentially I'm using paper-checkbox and paper-behaviors. The issue only shows up on first click of each instantiated item after that its fine. The checkbox has behaviors and doesn't act like its broken, but there is a console error. I included an image of the console. Using newest version of chrome, serving with gulp.

![error_ripple](https://cloud.githubusercontent.com/assets/4175471/10704305/dbf89d02-798a-11e5-9e39-8b4ce9b7795b.PNG)

my use:
paper-checkbox checked="{{task.completed}}"></paper-checkbox

my imports:
paper-behaviors/paper-button-behavior
paper-behaviors/paper-inky-focus-behavior
paper-behaviors/paper-ripple-behavior
paper-checkbox/paper-checkbox
paper-behaviors/paper-checked-element-behavior

**Comment by notwaldorf** [comment]
Did you update all of your dependencies, and not just `paper-checkbox`? There were some changes downstream that might affect this.

**Comment by jeremiahgibson91** [comment]
Yep that was it. I had updated them but it must have been a more recent change.
