### ISSUE TITLE
0 transform3D hack on chekcboxContainer

### ISSUE THREAD

**Issue by hypnoce** [PolymerElements/paper-checkbox#71]
Hello,

is there any reason to have a translateZ(0) on the checkbox container ? It creates a layer that needs compositing and might affect our goal of 60 fps on mobile devices.

Thanks

**Comment by notwaldorf** [comment]
I thiiiink it's goal is to bump the rendering to the GPU. /cc @frankiefu for halp

**Comment by frankiefu** [comment]
I don't remember why we added the `transform: translateZ(0)`.  Seems rendering fine now on Chrome.  Maybe we should remove it.

**Comment by hypnoce** [comment]
As far as I know, the checkbox is fully rendered on the CPU, but using a dedicated graphical layer.

As it seems to be good for animations, what it only does in the best case when animating, is only recalculating the style (depends on the style invalidation mechanism but it can affect more elements than just the checkbox), relayouting the first ancestor with a layout boundary, repainting the checkbox (or more elements which have been invalidated during relayout) on the CPU and then compose it with the already painted elements. Then, it has to rasterize the paints. In the worst case, its layer is squashed with another one, and thus all the previous step (from repaint) are applied to more elements.
For real GPU accelerated animation, see https://github.com/hypnoce/paper-checkbox/commit/375d57d913f6ace57bc53adc8992df85b028b60e 

Current checkbox implementation : 
![screen shot 2015-10-28 at 09 40 41](https://cloud.githubusercontent.com/assets/4430896/10783424/0c0b4b68-7d58-11e5-98e7-5356cdce28ff.png)

With GPU acceleration : 
![screen shot 2015-10-28 at 09 38 22](https://cloud.githubusercontent.com/assets/4430896/10783403/d3078df4-7d57-11e5-89ee-99e12fc25349.png)

Moreover, the GPU accelerated version only creates graphical layers when animating.
