### ISSUE TITLE
Checkbox not square for long labels

### ISSUE THREAD

**Issue by ronnyroeller** [PolymerElements/paper-checkbox#78]
The checkbox is not square if the label is longer than the available element space.

Example:
```html
<paper-checkbox>Very long option that squeezes the checkbox</paper-checkbox>
```

See the checkbox if the space is not sufficient:
![checkbox-squeezed](https://cloud.githubusercontent.com/assets/9339055/11245092/491fdf86-8e11-11e5-88d4-29834bd02fc3.png)

**Comment by notwaldorf** [comment]
This has been fixes in #79
