### ISSUE TITLE
--paper-checkbox-label-spacing Not Working

### ISSUE THREAD

**Issue by wbautistajr** [PolymerElements/paper-checkbox#80]
I've added styling for the paper-checkbox, but the --paper-checkbox-label-spacing attribute seems to be ignored. I've tried setting it to different values, but the spacing between the box and label is always 8px. Modifying other attributes, such as --paper-checkbox-checked-color, works as expected.

**Comment by notwaldorf** [comment]
Hmm, are you missing the `px` in your value, maybe? Here's a jsbin showing how it works: http://jsbin.com/pejoju/edit?html,output

**Comment by wbautistajr** [comment]
It was not a problem with px. We were using paper-checkbox 1.0.11. We've updated to paper-checkbox 1.0.14, and it works like a charm. Thanks.
