### ISSUE TITLE
paper-checkbox demo and its source are out-of-sync

### ISSUE THREAD

**Issue by remisbaima** [PolymerElements/paper-checkbox#86]
Demo code in: https://github.com/PolymerElements/paper-checkbox/blob/master/demo/index.html
does no reflect what we see in: https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html&active=paper-checkbox

**Comment by notwaldorf** [comment]
Looks good now! (needed a push to the catalog website)

**Comment by remisbaima** [comment]
Don't know if it is possible, but you could automate this task by auto pushing every time you commit in e.g.  https://github.com/PolymerElements/paper-checkbox/blob/master/demo/index.html
