### ISSUE TITLE
Switching checkbox and label positions

### ISSUE THREAD

**Issue by MoonDawg92** [PolymerElements/paper-checkbox#88]
Hey all,

Sorry if this has been brought up before, but I was not able to find an answer to my question. Basically, I would like to switch the label and checkbox positions for our system, but I haven't found a way to do this. This is what it looks like currently.
![checkbox](https://cloud.githubusercontent.com/assets/7232302/11728993/8c4a63d8-9f52-11e5-93ce-bc51e1c77a12.PNG)

I quickly photoshopped what I want it to look like. Is it possible to do this under the current version?
![checkbox2](https://cloud.githubusercontent.com/assets/7232302/11728996/8e2350f2-9f52-11e5-8555-3d076c2e279a.png)

Thanks!

**Comment by notwaldorf** [comment]
I think the easiest is using `dir=rtl` on the checkbox: http://jsbin.com/rihoxe/edit?html
