### ISSUE TITLE
How to set toggles=false in markup

### ISSUE THREAD

**Issue by grokys** [PolymerElements/paper-checkbox#89]
The documentation for `paper-checkbox` says that the `toggles` flag has a default of false, however this does not appear to be the case:

https://github.com/PolymerElements/iron-checked-element-behavior/blob/master/iron-checked-element-behavior.html#L52

Due to https://github.com/Polymer/polymer/issues/1812 it is impossible to use the following markup to clear the `toggles` flag:

    <paper-checkbox toggles="false>

What is the recommended way to set this property in markup?

**Comment by notwaldorf** [comment]
With HTML attributes (http://www.w3.org/TR/2008/WD-html5-20080610/semantics.html#boolean), you need to _remove_ the attribute altogether, not set it to false. So the markup you're looking for is
```<paper-checkbox></paper-checkbox>```

You can do this in JavaScript with
```this.removeAttribute('toggles');```

**Comment by grokys** [comment]
No, you've misunderstood. The point is that the *default* value of `toggles` is `true`. So removing the attribute leaves it at its default value, `true`. And because you cannot set HTML attributes to `false`, there appears to be no way to set `toggles` to false in markup.
