### ISSUE TITLE
binding checkbox with Angular 2.0

### ISSUE THREAD

**Issue by khoanguyenlio** [PolymerElements/paper-checkbox#92]
I have some issues like this
testChecked = false;
i use this attribute checked="{{testChecked}}" but its not working, this checkbox always checked.

**Comment by zoechi** [comment]
what about `[(checked)]="testChecked"`?

**Comment by khoanguyenlio** [comment]
It's working! Thank you <3

**Comment by notwaldorf** [comment]
Closing, as it seems figured out. Thanks @zoechi!
