### ISSUE TITLE
A `paper-checkbox` element with noink shows part of a ripple effect (a transparent circle) when right-clicked

### ISSUE THREAD

**Issue by mloechner** [PolymerElements/paper-checkbox#98]
## Expected outcome

When a checkbox with the noink attribute is right-clicked, it should not show any ripple effect at all.

## Actual outcome
![screen shot 2016-01-13 at 10 41 07 am](https://cloud.githubusercontent.com/assets/2047544/12299406/94fcd6bc-b9e4-11e5-8935-a021c0e28251.png)

The checkbox has a circle appear when right-clicked.

## Steps to reproduce

1. Put a `paper-checkbox` element in the page.
2. Open the page in a web browser.
3. Right click the `paper-checkbox` element.

This seemed to fix the problem for me:

```
paper-checkbox {
    --paper-checkbox-unchecked-ink-color: transparent;
    --paper-checkbox-checked-ink-color: transparent;
}
```

**Comment by notwaldorf** [comment]
That is not the ripple per se, that's the focus state of the checkbox (you can see this by tabbing to a checkbox as well, regardless of whether the checkbox has `noink`). When you right click on the checkbox, it becomes focused, and the focus state is displayed.

This is how native focusable elements work as well: http://jsbin.com/fuhate/edit?html,output. If you tab to any of the boxes, you'll see that they get a blue outline when focused. If you right click on an unfocused box, you'll notice it gets focused, and the outline is shown.
